/*
 * jabali-api
 *
 * API Proposal for Jabali.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package jabaliSDK

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

type JabaliAPI struct {
}

// Get /healthz
func (api *JabaliAPI) CheckHealth(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /game
// Create a new Game
func (api *JabaliAPI) CreateGame(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /game/:gameId
// Delete a game
func (api *JabaliAPI) DeleteGame(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /game/:gameId
// Get a Game
func (api *JabaliAPI) GetGame(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /games
// List Games
func (api *JabaliAPI) ListGames(c *gin.Context) {
	// Your handler implementation
	id := uuid.New()
	games := []Game{
		{DisplayName: "One", Name: "The Big One", Url: "https://google.com"},
	}
	games[0].GameId = id.String()
	c.IndentedJSON(http.StatusOK, games)
	//c.JSON(200, gin.H{"status": "OK"})
}

// Put /game/:gameId
// Update a game
func (api *JabaliAPI) UpdateGame(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
