/*
 * jabali-api
 *
 * API Proposal for Jabali.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package jabali_sdk

type Game struct {

	Name string `json:"name,omitempty"`

	DisplayName string `json:"displayName,omitempty"`

	GameId string `json:"gameId,omitempty"`

	Url string `json:"url,omitempty"`
}
