/*
 * jabali-api
 *
 * API Proposal for Jabali.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package jabaliSDK

type CreateGameRequest struct {

	Name string `json:"name"`

	DisplayName string `json:"displayName"`

	Url string `json:"url"`
}
